/**
 * Acceptance check: src/types/database.ts must match the coaching migration.
 *
 *   npx tsx scripts/coaching-types-check.ts
 *
 * WHY THIS EXISTS. The three coaching table blocks in `src/types/database.ts`
 * were HAND-TRANSCRIBED by reading the migration, not generated by the Supabase
 * CLI. Regenerating them needs a live database; verifying them does not. The
 * compiler will happily vouch for a shape the database does not have, and every
 * query in the coaching feature trusts that shape, so a silent mismatch here is
 * a runtime error the type system promises cannot happen.
 *
 * This reads the SQL DDL as the source of truth and the TS as the claim, and
 * fails on any disagreement. It is deliberately NOT a *.test.ts: tsconfig
 * excludes `scripts`, and this needs to run as a real program.
 *
 * THE RULES IT ENFORCES (Supabase codegen conventions):
 *   Row     - every column present; `| null` iff the column is nullable.
 *   Insert  - optional (`?`) iff the column has a DEFAULT or is nullable;
 *             required iff NOT NULL with no default.
 *   Update  - every column optional; nullability matches Row.
 *   types   - uuid/text/date/timestamptz -> string, integer/numeric -> number,
 *             boolean -> boolean.
 *
 * A CHECK constraint enumerating values (status, kind, source, ...) is NOT
 * expected to become a TS union: the Supabase generator emits plain `string`
 * for a bare text column regardless of its CHECK. Enforcing a union here would
 * fail against correctly-generated output.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(__dirname, '..')
const SQL_PATH = join(ROOT, 'supabase/migrations/20260907180000_coaching_engagements.sql')
const TS_PATH = join(ROOT, 'src/types/database.ts')

const TABLES = ['coaching_engagements', 'coaching_sessions', 'coaching_extractions']

interface SqlColumn {
  name: string
  sqlType: string
  notNull: boolean
  hasDefault: boolean
}

interface TsField {
  optional: boolean
  type: string
  nullable: boolean
}

/** Extract the parenthesised body of `create table ... public.<name> (` */
function tableBody(sql: string, table: string): string {
  const marker = new RegExp(`create table if not exists public\\.${table}\\s*\\(`, 'i')
  const m = marker.exec(sql)
  if (!m) throw new Error(`no create table found for ${table}`)
  let depth = 1
  let i = m.index + m[0].length
  const start = i
  while (i < sql.length && depth > 0) {
    const ch = sql[i]
    if (ch === '(') depth++
    else if (ch === ')') depth--
    i++
  }
  if (depth !== 0) throw new Error(`unbalanced parentheses in ${table}`)
  return sql.slice(start, i - 1)
}

/** Split a table body on commas that are at paren-depth 0. */
function splitTopLevel(body: string): string[] {
  const out: string[] = []
  let depth = 0
  let cur = ''
  for (const ch of body) {
    if (ch === '(') depth++
    if (ch === ')') depth--
    if (ch === ',' && depth === 0) { out.push(cur); cur = ''; continue }
    cur += ch
  }
  if (cur.trim()) out.push(cur)
  return out
}

function parseSqlColumns(sql: string, table: string): Map<string, SqlColumn> {
  const cols = new Map<string, SqlColumn>()
  // Strip `--` comments BEFORE splitting on commas. A comment can contain a
  // comma ("$8,500 average job value, per month") and splitting first tears the
  // column definition in half.
  const body = tableBody(sql, table)
    .split('\n')
    .map((l) => l.replace(/--.*$/, ''))
    .join('\n')
  for (const rawPart of splitTopLevel(body)) {
    const part = rawPart.split('\n').join(' ').replace(/\s+/g, ' ').trim()
    if (!part) continue
    if (/^constraint\b/i.test(part)) continue
    if (/^(primary key|unique|check|foreign key)\b/i.test(part)) continue

    // `name type` or `name type(3, 2)`
    const m = /^([a-z_][a-z0-9_]*)\s+([a-z ]+?(?:\([^)]*\))?)(?:\s|$)/i.exec(part)
    if (!m) throw new Error(`could not parse column definition in ${table}: ${part.slice(0, 60)}`)
    const name = m[1]
    const sqlType = m[2].trim().toLowerCase()
    cols.set(name, {
      name,
      sqlType,
      // PRIMARY KEY implies NOT NULL in Postgres even when it is not written.
      // Without this, `id uuid primary key default ...` reads as nullable and
      // the check fires against correct TS.
      notNull: /\bnot\s+null\b/i.test(part) || /\bprimary\s+key\b/i.test(part),
      hasDefault: /\bdefault\b/i.test(part),
    })
  }
  return cols
}

/** Pull `<table>: { Row: {...} Insert: {...} Update: {...} }` out of database.ts */
function parseTsTable(ts: string, table: string): Record<string, Map<string, TsField>> {
  const start = ts.indexOf(`      ${table}: {`)
  if (start === -1) throw new Error(`no TS block found for ${table}`)
  const result: Record<string, Map<string, TsField>> = {}
  for (const section of ['Row', 'Insert', 'Update']) {
    const secStart = ts.indexOf(`        ${section}: {`, start)
    if (secStart === -1) throw new Error(`no ${section} block for ${table}`)
    const secEnd = ts.indexOf('\n        }', secStart)
    const body = ts.slice(secStart, secEnd)
    const fields = new Map<string, TsField>()
    for (const line of body.split('\n').slice(1)) {
      const m = /^\s{10}([a-z_][a-z0-9_]*)(\??):\s*(.+?)\s*$/i.exec(line)
      if (!m) continue
      const type = m[3]
      fields.set(m[1], {
        optional: m[2] === '?',
        type,
        nullable: /\|\s*null/.test(type),
      })
    }
    if (fields.size === 0) throw new Error(`parsed 0 fields for ${table}.${section}`)
    result[section] = fields
  }
  return result
}

function expectedTsType(sqlType: string): string {
  if (/^uuid|^text|^date|^timestamptz|^timestamp/.test(sqlType)) return 'string'
  if (/^integer|^bigint|^numeric|^smallint|^real|^double/.test(sqlType)) return 'number'
  if (/^boolean/.test(sqlType)) return 'boolean'
  if (/^jsonb?/.test(sqlType)) return 'Json'
  throw new Error(`unmapped SQL type: ${sqlType}`)
}

const problems: string[] = []
const sql = readFileSync(SQL_PATH, 'utf8')
const ts = readFileSync(TS_PATH, 'utf8')
let checked = 0

for (const table of TABLES) {
  const sqlCols = parseSqlColumns(sql, table)
  const tsBlocks = parseTsTable(ts, table)

  for (const section of ['Row', 'Insert', 'Update'] as const) {
    const fields = tsBlocks[section]

    for (const name of fields.keys()) {
      if (!sqlCols.has(name)) problems.push(`${table}.${section}.${name}: in TS but NOT in the migration`)
    }

    for (const col of sqlCols.values()) {
      const f = fields.get(col.name)
      if (!f) { problems.push(`${table}.${section}.${col.name}: in the migration but MISSING from TS`); continue }
      checked++

      const base = expectedTsType(col.sqlType)
      if (!f.type.startsWith(base)) {
        problems.push(`${table}.${section}.${col.name}: SQL ${col.sqlType} => expected ${base}, TS has ${f.type}`)
      }

      const shouldBeNullable = !col.notNull
      if (f.nullable !== shouldBeNullable) {
        problems.push(
          `${table}.${section}.${col.name}: column is ${col.notNull ? 'NOT NULL' : 'nullable'}, ` +
          `so TS ${shouldBeNullable ? 'must' : 'must not'} include "| null" — got ${f.type}`,
        )
      }

      const shouldBeOptional =
        section === 'Update' ? true : section === 'Insert' ? col.hasDefault || !col.notNull : false
      if (f.optional !== shouldBeOptional) {
        problems.push(
          `${table}.${section}.${col.name}: expected ${shouldBeOptional ? 'optional (?)' : 'required'} ` +
          `(not null=${col.notNull}, default=${col.hasDefault}) — got ${f.optional ? 'optional' : 'required'}`,
        )
      }
    }
  }
}

if (problems.length > 0) {
  for (const p of problems) console.error(`FAIL  ${p}`)
  console.error(`\nFAIL: ${problems.length} mismatch(es) between database.ts and the migration`)
  process.exit(1)
}

console.log(`PASS: ${TABLES.length} tables, ${checked} column assertions — database.ts matches the migration`)
