"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { motion } from "framer-motion";
import { supabaseClient } from "@/lib/supabase/client";
import { Zap, Cpu } from "lucide-react";

const SECTIONS = [
  {
    number: "01",
    title: "Opportunity",
    content: "Australia's restoration, compliance, and field-services industries are under-served by software. Unite Group has identified a $50M+ TAM across 6 verticals where incumbent tools are legacy or absent. The thesis: acquire founder-led businesses at 3–5x ARR, inject Pi-CEO automation, exit at 8–12x ARR within 48 months.",
  },
  {
    number: "02",
    title: "Strategy",
    content: "Three-phase playbook: (1) Validate with CCW — prove the Pi-CEO stack on a paying client delivering measurable CRM + campaign ROI. (2) Build momentum — RestoreAssist App Store launch, Synthex SaaS platform, NRPG community flywheel. (3) Consolidate — CARSI compliance revenue, DR Platform, portfolio acquisition fund.",
  },
  {
    number: "03",
    title: "Current State",
    content: "6 portfolio businesses. 1 paying client (CCW, $2,400/yr ARR). 4 Pi-CEO agents live. Synthex at 40/85 content assets. RestoreAssist on TestFlight. Unite-Hub platform rebuilt with zinc design system. SEO pipeline active across all 6 domains. Monthly burn: managed. Runway: 6+ months.",
  },
  {
    number: "04",
    title: "Goals — Next 90 Days",
    content: "1. CCW → $5,000 ARR (upsell SEO package). 2. RestoreAssist → App Store live. 3. Synthex → 85/85 content assets published. 4. NRPG → contractor onboarding flow. 5. Pi-CEO → 8 agents live, automated weekly brief. 6. Unite-Hub → client portal v2 for 2 new clients.",
  },
  {
    number: "05",
    title: "People & Org",
    content: "Phill McGurk — Founder & CEO, product + strategy. Pi-CEO swarm — 4 live agents (health-monitor, gap-detector, wiki-ingest, brief-generator). Development team: Yasir (lead), Afifa, Usman. Design: Ayesha, Amina, Shahid. Marketing: Claire Booth. Headcount target: +2 senior engineers Q3.",
  },
  {
    number: "06",
    title: "Actions — This Week",
    content: "[ ] Publish CCW SEO audit report. [ ] RestoreAssist TestFlight build 1.2.3. [ ] Synthex: 5 blog posts drafted. [ ] Pi-CEO: wire health-monitor to Slack alerts. [ ] Unite-Hub: deploy zinc modernization. [ ] NRPG: contractor onboarding wireframe review. [ ] Board minutes: file this 6-pager.",
  },
];

const card: React.CSSProperties = {
  background: "#111113",
  border: "1px solid #27272a",
  borderRadius: 12,
  padding: 24,
};

export default function SixPagerBrief() {
  const router = useRouter();
  const [loaded, setLoaded] = useState(false);
  const [sections, setSections] = useState(SECTIONS.map(s => ({ ...s })));

  useEffect(() => {
    supabaseClient.auth.getSession().then(({ data: { session } }) => {
      if (!session) { router.push("/login"); return; }
      setLoaded(true);
    });
  }, [router]);

  if (!loaded) return (
    <div style={{ minHeight: "100vh", background: "#09090b", display: "flex", alignItems: "center", justifyContent: "center" }}>
      <Zap size={20} color="#334155" />
    </div>
  );

  return (
    <div style={{ minHeight: "100vh", background: "#09090b", color: "#f8fafc" }}>

      {/* Page title */}
      <div style={{ padding: "24px 24px 0", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div>
          <h1 style={{ fontSize: 18, fontWeight: 700, color: "#fafafa", letterSpacing: "-0.02em", margin: 0, fontFamily: "var(--font-display)" }}>
            Empire 6-Pager
          </h1>
          <p style={{ fontSize: 11, color: "#52525b", margin: "3px 0 0", fontFamily: "var(--font-mono)" }}>Weekly strategic brief — Unite Group portfolio</p>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 6, padding: "4px 10px", background: "rgba(29,78,216,0.1)", border: "1px solid rgba(29,78,216,0.2)", borderRadius: 20 }}>
          <Cpu size={11} color="#3b82f6" />
          <span style={{ fontSize: 10, fontWeight: 600, color: "#3b82f6", letterSpacing: "0.04em" }}>Generated by Pi-CEO</span>
        </div>
      </div>

      <main style={{ maxWidth: 1100, margin: "0 auto", padding: "32px 24px 64px", display: "flex", flexDirection: "column", gap: 20 }}>

        <div style={{ marginBottom: 8 }}>
          <p style={{ fontSize: 14, color: "#475569", margin: 0 }}>Edit any section below.</p>
        </div>

        {sections.map((section, i) => (
          <motion.div
            key={section.number}
            style={card}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: i * 0.06, ease: [0.23, 1, 0.32, 1] }}
          >
            <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 14 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, fontWeight: 600, color: "#334155" }}>{section.number}</span>
                <h2 style={{ fontSize: 16, fontWeight: 600, color: "#f8fafc", letterSpacing: "-0.02em", margin: 0 }}>{section.title}</h2>
              </div>
              <span style={{ fontSize: 10, fontWeight: 600, color: "#334155", letterSpacing: "0.06em", textTransform: "uppercase", flexShrink: 0 }}>editable</span>
            </div>
            <textarea
              value={section.content}
              onChange={e => {
                const updated = [...sections];
                updated[i] = { ...updated[i], content: e.target.value };
                setSections(updated);
              }}
              rows={4}
              style={{
                width: "100%",
                background: "#18181b",
                border: "1px solid #27272a",
                borderRadius: 8,
                padding: "12px 14px",
                fontSize: 14,
                color: "#94a3b8",
                lineHeight: 1.6,
                resize: "vertical",
                outline: "none",
                fontFamily: "var(--font-display)",
                boxSizing: "border-box",
                transition: "border-color 0.12s ease",
              }}
              onFocus={e => (e.target.style.borderColor = "#334155")}
              onBlur={e => (e.target.style.borderColor = "#27272a")}
            />
          </motion.div>
        ))}

        <div style={{ display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 8 }}>
          <Link
            href="/dashboard/ceo"
            style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "8px 14px", borderRadius: 8, fontSize: 13, fontWeight: 500, color: "#94a3b8", border: "1px solid #27272a", textDecoration: "none", background: "transparent", transition: "all 0.12s ease" }}
            onMouseEnter={e => { (e.currentTarget as HTMLAnchorElement).style.background = "#18181b"; (e.currentTarget as HTMLAnchorElement).style.color = "#f8fafc"; }}
            onMouseLeave={e => { (e.currentTarget as HTMLAnchorElement).style.background = "transparent"; (e.currentTarget as HTMLAnchorElement).style.color = "#94a3b8"; }}
          >
            Back to Command Center
          </Link>
        </div>
      </main>
    </div>
  );
}
