-- ============================================================
-- Weekly Reviews — durable founder-scoped weekly brief
--
-- The pi-ceo-weekly-review cron generates a rich weekly brief but currently
-- upserts it inside a try/catch that swallows "table may not exist" — so the
-- brief was never persisted. This table makes it durable. Founder-scoped,
-- additive, no secrets.
--
-- Mirrors the upsert shape in src/app/api/cron/pi-ceo-weekly-review/route.ts
-- (onConflict: founder_id,review_period_start).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.weekly_reviews (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  founder_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  review_period_start  DATE NOT NULL,
  headline             TEXT NOT NULL,
  brief_md             TEXT NOT NULL,
  metrics              JSONB NOT NULL DEFAULT '{}',
  decisions_queue      JSONB NOT NULL DEFAULT '[]',
  next_priorities      JSONB NOT NULL DEFAULT '[]',
  status               TEXT NOT NULL DEFAULT 'new'
                       CHECK (status IN ('new', 'reviewed', 'archived')),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(founder_id, review_period_start)
);

COMMENT ON TABLE public.weekly_reviews IS 'Founder-scoped weekly Pi-CEO review briefs generated by the pi-ceo-weekly-review cron';

CREATE INDEX IF NOT EXISTS weekly_reviews_founder_period_idx
  ON public.weekly_reviews(founder_id, review_period_start DESC);

ALTER TABLE public.weekly_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS weekly_reviews_select ON public.weekly_reviews;
CREATE POLICY weekly_reviews_select ON public.weekly_reviews
  FOR SELECT USING (founder_id = auth.uid());

DROP POLICY IF EXISTS weekly_reviews_insert ON public.weekly_reviews;
CREATE POLICY weekly_reviews_insert ON public.weekly_reviews
  FOR INSERT WITH CHECK (founder_id = auth.uid());

DROP POLICY IF EXISTS weekly_reviews_update ON public.weekly_reviews;
CREATE POLICY weekly_reviews_update ON public.weekly_reviews
  FOR UPDATE USING (founder_id = auth.uid())
  WITH CHECK (founder_id = auth.uid());

CREATE OR REPLACE FUNCTION public.weekly_reviews_update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS weekly_reviews_updated_at ON public.weekly_reviews;
CREATE TRIGGER weekly_reviews_updated_at
  BEFORE UPDATE ON public.weekly_reviews
  FOR EACH ROW EXECUTE FUNCTION public.weekly_reviews_update_updated_at();

-- NOTE: the cron writes with the SERVICE ROLE (bypasses RLS); these policies are
-- defence-in-depth for any future session-scoped read of the founder's reviews.

-- DOWN / rollback
-- DROP TRIGGER IF EXISTS weekly_reviews_updated_at ON public.weekly_reviews;
-- DROP FUNCTION IF EXISTS public.weekly_reviews_update_updated_at();
-- DROP POLICY IF EXISTS weekly_reviews_update ON public.weekly_reviews;
-- DROP POLICY IF EXISTS weekly_reviews_insert ON public.weekly_reviews;
-- DROP POLICY IF EXISTS weekly_reviews_select ON public.weekly_reviews;
-- DROP INDEX IF EXISTS weekly_reviews_founder_period_idx;
-- DROP TABLE IF EXISTS public.weekly_reviews;
