import crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { redactSensitiveText } from './redaction';
import type { ApprovalGate, ApprovalGateApplyRequest } from './approval-gate';

export type TelegramDecisionAction = 'approve' | 'reject' | 'defer' | 'request_changes' | 'view_evidence';
export type TelegramDecisionActionCode = 'A' | 'R' | 'D' | 'C' | 'V';
export type DecisionResultState = 'terminal' | 'non_terminal' | 'info_only';
export type TelegramDecisionErrorCode = 'ERR_PARSE' | 'ERR_BAD_VERSION' | 'ERR_BAD_ACTION' | 'ERR_BAD_FORMAT' | 'ERR_BAD_SIG' | 'ERR_REPLAY' | 'ERR_NOT_PENDING' | 'ERR_NOT_FOUND' | 'ERR_NOT_AUTHORIZED' | 'ERR_TERMINAL_LOCKED' | 'ERR_INTERNAL';
export interface TelegramCallbackContext { chatId: string; userId: string; nowMs?: number }
export interface DecodedDecisionPayload { version: 'h1'; action: TelegramDecisionAction; actionCode: TelegramDecisionActionCode; applyRequestShortId: string; nonce: string; signature: string; raw: string }
export interface Phase1IDecisionRecord { decisionId: string; phase: '1I'; applyRequestId: string; source: 'telegram-inline'; action: TelegramDecisionAction; actor: { telegramUserId: string; telegramUsername?: string; displayName?: string }; chat: { chatId: string; messageId: number }; nonce: string; verified: true; verifiedAt: string; resultState: DecisionResultState; notes?: string; createdAt: string; noSideEffectDeclaration: true }
export interface TelegramInlineKeyboardButton { text: string; callback_data: string }
export interface TelegramInlineKeyboardMarkup { inline_keyboard: TelegramInlineKeyboardButton[][] }
const A2C: Record<TelegramDecisionAction, TelegramDecisionActionCode> = { approve: 'A', reject: 'R', defer: 'D', request_changes: 'C', view_evidence: 'V' };
const C2A: Record<TelegramDecisionActionCode, TelegramDecisionAction> = { A: 'approve', R: 'reject', D: 'defer', C: 'request_changes', V: 'view_evidence' };
const LABELS: Record<TelegramDecisionAction, string> = { approve: '✅ Approve', reject: '❌ Reject', defer: '⏸ Defer', request_changes: '📝 Request Changes', view_evidence: '🔍 View Evidence' };
const b64 = (buf: Buffer | string): string => (Buffer.isBuffer(buf) ? buf : Buffer.from(buf)).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
const tsBucket = (nowMs: number, minutes: number): number => Math.floor(nowMs / (minutes * 60_000));
const canonical = (v: 'h1', a: TelegramDecisionActionCode, r: string, n: string, chat: string, user: string, b: number): string => [v, a, r, n, chat, user, String(b)].join('|');
const sig = (value: string, key: string, len: number): string => b64(crypto.createHmac('sha256', key).update(value).digest()).slice(0, len);
function safeEqual(a: string, b: string): boolean { const left = Buffer.from(a); const right = Buffer.from(b); return left.length === right.length && crypto.timingSafeEqual(new Uint8Array(left), new Uint8Array(right)); }
export const actionToResultState = (action: TelegramDecisionAction): DecisionResultState => action === 'approve' || action === 'reject' ? 'terminal' : action === 'view_evidence' ? 'info_only' : 'non_terminal';
export const createApplyRequestShortId = (id: string): string => { if (!id.trim()) throw new Error('Invalid Phase 1I Telegram decision: applyRequestId is required'); return b64(crypto.createHash('sha256').update(id).digest()).slice(0, 10); };
export const createDecisionNonce = (): string => b64(crypto.randomBytes(5)).slice(0, 8);
export function encodeDecisionCallbackData(input: { action: TelegramDecisionAction; applyRequestShortId: string; nonce: string; context: TelegramCallbackContext; signingKey: string; version?: 'h1'; sigLen?: number; bucketMinutes?: number }): string {
  const v = input.version ?? 'h1'; const len = input.sigLen ?? 10; const mins = input.bucketMinutes ?? 1; if (!input.signingKey || !/^[a-zA-Z0-9_-]{8,12}$/.test(input.applyRequestShortId) || !/^[a-zA-Z0-9_-]{6,8}$/.test(input.nonce)) throw new Error('ERR_BAD_FORMAT');
  const code = A2C[input.action]; const signature = sig(canonical(v, code, input.applyRequestShortId, input.nonce, input.context.chatId, input.context.userId, tsBucket(input.context.nowMs ?? Date.now(), mins)), input.signingKey, len); const data = `${v}|${code}|${input.applyRequestShortId}|${input.nonce}|${signature}`; if (data.length > 64) throw new Error('callback_data too long'); return data;
}
export function decodeDecisionCallbackData(data: string): DecodedDecisionPayload { const p = data.split('|'); if (p.length !== 5) throw new Error('ERR_BAD_FORMAT'); const [v, c, r, n, s] = p; if (v !== 'h1') throw new Error('ERR_BAD_VERSION'); if (!/^[ARDCV]$/.test(c)) throw new Error('ERR_BAD_ACTION'); if (!/^[a-zA-Z0-9_-]{8,12}$/.test(r) || !/^[a-zA-Z0-9_-]{6,8}$/.test(n) || !/^[a-zA-Z0-9_-]{8,16}$/.test(s)) throw new Error('ERR_BAD_FORMAT'); const actionCode = c as TelegramDecisionActionCode; return { version: 'h1', actionCode, action: C2A[actionCode], applyRequestShortId: r, nonce: n, signature: s, raw: data }; }
export function verifyDecisionCallbackData(input: { callbackData: string; context: TelegramCallbackContext; signingKey: string; sigLen?: number; bucketMinutes?: number; allowPreviousBucket?: boolean; replaySeen?: (key: string) => boolean }): { ok: boolean; code?: TelegramDecisionErrorCode; payload?: DecodedDecisionPayload; idempotencyKey?: string } { let payload: DecodedDecisionPayload; try { payload = decodeDecisionCallbackData(input.callbackData); } catch (e) { return { ok: false, code: e instanceof Error ? e.message as TelegramDecisionErrorCode : 'ERR_PARSE' }; } const len = input.sigLen ?? 10; const mins = input.bucketMinutes ?? 1; const b = tsBucket(input.context.nowMs ?? Date.now(), mins); const buckets = input.allowPreviousBucket ?? true ? [b, b - 1] : [b]; const valid = buckets.some((x) => safeEqual(sig(canonical(payload.version, payload.actionCode, payload.applyRequestShortId, payload.nonce, input.context.chatId, input.context.userId, x), input.signingKey, len), payload.signature)); if (!valid) return { ok: false, code: 'ERR_BAD_SIG' as const }; const idempotencyKey = `${payload.applyRequestShortId}:${payload.actionCode}:${input.context.userId}:${payload.nonce}`; if (input.replaySeen?.(idempotencyKey)) return { ok: false, code: 'ERR_REPLAY' as const, payload, idempotencyKey }; return { ok: true, payload, idempotencyKey }; }
export function readPhase1IDecisionLedger(file: string): Phase1IDecisionRecord[] { if (!fs.existsSync(file)) return []; const raw = fs.readFileSync(file, 'utf8').trim(); return raw ? raw.split('\n').map((l) => JSON.parse(l) as Phase1IDecisionRecord) : []; }
export function resolveApplyRequestByShortId(gate: ApprovalGate, shortId: string): ApprovalGateApplyRequest { const found = gate.applyRequests.filter((r) => createApplyRequestShortId(r.id) === shortId); if (found.length !== 1) throw new Error('ERR_NOT_FOUND'); return found[0]; }
function assertPending(r: ApprovalGateApplyRequest): void { if (r.applyState !== 'pending_human_gate') throw new Error('ERR_NOT_PENDING'); if (!r.requiresHumanApproval || !r.noSideEffectDeclaration) throw new Error('ERR_NOT_AUTHORIZED'); }
export function buildPhase1IDecisionRecord(input: { applyRequestId: string; payload: DecodedDecisionPayload; chatId: string; messageId: number; actor: { telegramUserId: string; telegramUsername?: string; displayName?: string }; notes?: string; nowIso?: string; decisionIdFactory?: () => string }): Phase1IDecisionRecord { const now = input.nowIso ?? new Date().toISOString(); return { decisionId: input.decisionIdFactory?.() ?? `dec_${now.replace(/[-:.TZ]/g, '').slice(0, 14)}_${createDecisionNonce()}`, phase: '1I', applyRequestId: redactSensitiveText(input.applyRequestId), source: 'telegram-inline', action: input.payload.action, actor: { telegramUserId: redactSensitiveText(input.actor.telegramUserId), ...(input.actor.telegramUsername ? { telegramUsername: redactSensitiveText(input.actor.telegramUsername) } : {}), ...(input.actor.displayName ? { displayName: redactSensitiveText(input.actor.displayName) } : {}) }, chat: { chatId: redactSensitiveText(input.chatId), messageId: input.messageId }, nonce: input.payload.nonce, verified: true, verifiedAt: now, resultState: actionToResultState(input.payload.action), ...(input.notes ? { notes: redactSensitiveText(input.notes) } : {}), createdAt: now, noSideEffectDeclaration: true }; }
export function getDecisionState(file: string, id: string) { const decisions = readPhase1IDecisionLedger(file).filter((r) => r.applyRequestId === id && r.action !== 'view_evidence'); const terminal = decisions.find((r) => r.resultState === 'terminal'); const last = decisions[decisions.length - 1]; const chosen = terminal ?? last; const who = chosen?.actor.displayName ?? chosen?.actor.telegramUsername ?? chosen?.actor.telegramUserId; return { applyRequestId: id, decisions, finalAction: terminal?.action as 'approve' | 'reject' | undefined, isTerminal: Boolean(terminal), summary: terminal ? `Decision state: ${terminal.action} by ${who} at ${terminal.createdAt} (terminal)` : last ? `Decision state: ${last.action} by ${who} at ${last.createdAt} (non-terminal)` : 'Decision state: pending_human_gate with no Phase 1I decisions recorded' }; }
export function appendVerifiedPhase1IDecision(input: { gate: ApprovalGate; ledgerPath: string; applyRequestId: string; payload: DecodedDecisionPayload; chatId: string; messageId: number; actor: { telegramUserId: string; telegramUsername?: string; displayName?: string }; notes?: string; nowIso?: string; decisionIdFactory?: () => string }) { const req = resolveApplyRequestByShortId(input.gate, input.payload.applyRequestShortId); if (req.id !== input.applyRequestId) throw new Error('ERR_NOT_FOUND'); assertPending(req); if (input.payload.action === 'view_evidence') throw new Error('ERR_BAD_ACTION'); fs.mkdirSync(path.dirname(input.ledgerPath), { recursive: true }); if (fs.existsSync(input.ledgerPath) && fs.lstatSync(input.ledgerPath).isSymbolicLink()) throw new Error('ERR_INTERNAL'); const existing = readPhase1IDecisionLedger(input.ledgerPath).filter((r) => r.applyRequestId === input.applyRequestId); const dup = existing.find((r) => r.nonce === input.payload.nonce && r.actor.telegramUserId === input.actor.telegramUserId); if (dup) return { record: dup, state: getDecisionState(input.ledgerPath, input.applyRequestId), appended: false }; const terminal = existing.find((r) => r.resultState === 'terminal'); if (terminal) { if (terminal.action === input.payload.action) return { record: terminal, state: getDecisionState(input.ledgerPath, input.applyRequestId), appended: false }; throw new Error('ERR_TERMINAL_LOCKED'); } const record = buildPhase1IDecisionRecord(input); fs.appendFileSync(input.ledgerPath, `${JSON.stringify(record)}\n`); return { record, state: getDecisionState(input.ledgerPath, input.applyRequestId), appended: true }; }
export function replaySeenInLedger(file: string, key: string): boolean { const [shortId, actionCode, userId, nonce] = key.split(':'); return readPhase1IDecisionLedger(file).some((r) => createApplyRequestShortId(r.applyRequestId) === shortId && A2C[r.action] === actionCode && r.actor.telegramUserId === userId && r.nonce === nonce); }
export function buildTelegramApprovalKeyboard(input: { applyRequestId: string; context: TelegramCallbackContext; signingKey: string; nonceFactory?: () => string }): TelegramInlineKeyboardMarkup { const short = createApplyRequestShortId(input.applyRequestId); const button = (action: TelegramDecisionAction) => ({ text: LABELS[action], callback_data: encodeDecisionCallbackData({ action, applyRequestShortId: short, nonce: input.nonceFactory?.() ?? createDecisionNonce(), context: input.context, signingKey: input.signingKey }) }); return { inline_keyboard: [[button('approve'), button('reject')], [button('defer'), button('request_changes')], [button('view_evidence')]] }; }
export function renderTelegramApprovalNotification(request: ApprovalGateApplyRequest, context: TelegramCallbackContext, signingKey: string) { assertPending(request); return { text: [`Phase 1H approval request: ${redactSensitiveText(request.title)}`, `Apply request: ${redactSensitiveText(request.id)}`, `Requested action: ${request.requestedActionType}`, `Risk: ${request.riskLevel}`, `State: ${request.applyState}`, 'Phase 1I quick decision only. No execution path is available from these buttons.'].join('\n'), reply_markup: buildTelegramApprovalKeyboard({ applyRequestId: request.id, context, signingKey }) }; }
export function createEvidenceSummary(gate: ApprovalGate, id: string): string { const req = gate.applyRequests.find((r) => r.id === id) ?? resolveApplyRequestByShortId(gate, id); assertPending(req); return [`Evidence for ${redactSensitiveText(req.id)}`, `Title: ${redactSensitiveText(req.title)}`, `Requested action: ${req.requestedActionType}`, `Risk: ${req.riskLevel}`, 'Evidence refs:', ...req.evidenceRefs.slice(0, 5).map((ref) => `- ${redactSensitiveText(ref)}`), 'No execution side effects. Evidence view only.'].join('\n'); }
