import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

interface RouteEntry {
  path: string;
  file: string;
  methods: string[];
  authWrapped: boolean;
  rateLimitWrapped: boolean;
  csrfWrapped: boolean;
  inputValidated: boolean;
  webhookSignature: boolean;
  notes: string;
}

// Patterns that count as "this request is authenticated by something" — covers
// wrapper helpers, inline supabase session checks, and cryptographic webhook
// signature verification. The audit treats any of these as authenticated.
const AUTH_PATTERNS = [
  /withAuth|requireAuth|verifyAdminJwt|getServerSession|getAdminSession/,
  /timingSafeBearerMatch|withSyncLifecycle/,
  /supabase\.auth\.(getSession|getUser)/,
];
const WEBHOOK_SIGNATURE_PATTERNS = [
  /verifyStripeSignature|webhooks\.constructEvent/,
  /verifyWebhookSignature|verifySignature/,
];

function walk(dir: string, baseUrl = ""): RouteEntry[] {
  const out: RouteEntry[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      out.push(...walk(full, `${baseUrl}/${entry}`));
    } else if (entry === "route.ts") {
      const content = readFileSync(full, "utf-8");
      const webhookSignature = WEBHOOK_SIGNATURE_PATTERNS.some((re) => re.test(content));
      const authWrapped =
        AUTH_PATTERNS.some((re) => re.test(content)) || webhookSignature;
      out.push({
        path: baseUrl || "/",
        file: full,
        methods: ["GET","POST","PUT","PATCH","DELETE"].filter((m) =>
          new RegExp(`export\\s+(async\\s+)?function\\s+${m}\\b|export\\s+const\\s+${m}\\s*=`).test(content)),
        authWrapped,
        rateLimitWrapped: /withRateLimit|\brateLimit\s*\(|RATE_LIMITS\./i.test(content),
        csrfWrapped: /validateCsrf|csrfToken/.test(content),
        inputValidated: /\.safeParse\(|\.parse\(|zod|\bSchema\./.test(content),
        webhookSignature,
        notes: "",
      });
    }
  }
  return out;
}

const routes = walk("src/app/api", "/api").sort((a, b) => a.path.localeCompare(b.path));

const header = `# Unite-Group API Route Inventory

> Generated by \`scripts/generate-route-inventory.ts\` on ${new Date().toISOString().slice(0, 10)}.
> Re-run via \`npx ts-node --transpile-only -O '{"module":"commonjs","moduleResolution":"node"}' scripts/generate-route-inventory.ts\`.

**Auth column legend:** \`✓\` = wrapper / session / JWT check, \`S\` = cryptographic webhook signature verification (Stripe HMAC etc. — different model, treated as authenticated), \`✗\` = no detected auth.

| Route | Methods | Auth | RateLimit | CSRF | InputValidated | File |
| --- | --- | --- | --- | --- | --- | --- |
`;

const authGlyph = (r: RouteEntry) =>
  r.webhookSignature ? "S" : r.authWrapped ? "✓" : "✗";

const rows = routes.map((r) =>
  `| \`${r.path}\` | ${r.methods.join(", ")} | ${authGlyph(r)} | ${r.rateLimitWrapped ? "✓" : "✗"} | ${r.csrfWrapped ? "✓" : "✗"} | ${r.inputValidated ? "✓" : "✗"} | \`${r.file.replace(process.cwd() + "/", "")}\` |`
).join("\n");

const total = routes.length;
const pct = (n: number) => total === 0 ? 0 : Math.round((n / total) * 100);
const authCount = routes.filter((r) => r.authWrapped && !r.webhookSignature).length;
const sigCount = routes.filter((r) => r.webhookSignature).length;
const rlCount = routes.filter((r) => r.rateLimitWrapped).length;
const csrfCount = routes.filter((r) => r.csrfWrapped).length;
const inputCount = routes.filter((r) => r.inputValidated).length;

const summary = `

## Summary

- Total routes: ${total}
- Auth-wrapped (session / JWT / bearer): ${authCount} (${pct(authCount)}%)
- Webhook-signature-verified: ${sigCount} (${pct(sigCount)}%)
- Rate-limited: ${rlCount} (${pct(rlCount)}%)
- CSRF-protected: ${csrfCount} (${pct(csrfCount)}%)
- Input-validated: ${inputCount} (${pct(inputCount)}%)

## Highest-priority gaps

Routes that accept mutating methods (POST / PUT / PATCH / DELETE) AND have **no auth, no webhook signature, no rate-limit**:

| Route | Methods | File |
| --- | --- | --- |
${routes
  .filter((r) => !r.authWrapped && !r.rateLimitWrapped && r.methods.some((m) => ["POST","PUT","PATCH","DELETE"].includes(m)))
  .map((r) => `| \`${r.path}\` | ${r.methods.join(", ")} | \`${r.file.replace(process.cwd() + "/", "")}\` |`)
  .join("\n") || "_(none — every mutating route has at least auth, a webhook signature, or a rate-limit)_"}
`;

const outPath = "docs/security/route-inventory.md";
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, header + rows + summary);
console.log(`Wrote ${total} routes to ${outPath}`);
