import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

interface RouteEntry {
  path: string;
  file: string;
  methods: string[];
  authWrapped: boolean;
  rateLimitWrapped: boolean;
  csrfWrapped: boolean;
  inputValidated: boolean;
  notes: string;
}

function walk(dir: string, baseUrl = ""): RouteEntry[] {
  const out: RouteEntry[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      out.push(...walk(full, `${baseUrl}/${entry}`));
    } else if (entry === "route.ts") {
      const content = readFileSync(full, "utf-8");
      out.push({
        path: baseUrl || "/",
        file: full,
        methods: ["GET","POST","PUT","PATCH","DELETE"].filter((m) =>
          new RegExp(`export\\s+(async\\s+)?function\\s+${m}\\b|export\\s+const\\s+${m}\\s*=`).test(content)),
        authWrapped: /withAuth|requireAuth|verifyAdminJwt|getServerSession|getAdminSession|timingSafeBearerMatch|withSyncLifecycle/.test(content),
        rateLimitWrapped: /applyRateLimit|withRateLimit|rate-?limit/i.test(content),
        csrfWrapped: /validateCsrf|csrfToken/.test(content),
        inputValidated: /\.safeParse\(|\.parse\(|zod|\bSchema\./.test(content),
        notes: "",
      });
    }
  }
  return out;
}

const routes = walk("src/app/api", "/api").sort((a, b) => a.path.localeCompare(b.path));

const header = `# Unite-Group API Route Inventory

> Generated by \`scripts/generate-route-inventory.ts\` on ${new Date().toISOString().slice(0, 10)}.
> Re-run via \`npx ts-node --transpile-only -O '{"module":"commonjs","moduleResolution":"node"}' scripts/generate-route-inventory.ts\`.

| Route | Methods | Auth | RateLimit | CSRF | InputValidated | File |
| --- | --- | --- | --- | --- | --- | --- |
`;

const rows = routes.map((r) =>
  `| \`${r.path}\` | ${r.methods.join(", ")} | ${r.authWrapped ? "✓" : "✗"} | ${r.rateLimitWrapped ? "✓" : "✗"} | ${r.csrfWrapped ? "✓" : "✗"} | ${r.inputValidated ? "✓" : "✗"} | \`${r.file.replace(process.cwd() + "/", "")}\` |`
).join("\n");

const total = routes.length;
const pct = (n: number) => total === 0 ? 0 : Math.round((n / total) * 100);
const authCount = routes.filter((r) => r.authWrapped).length;
const rlCount = routes.filter((r) => r.rateLimitWrapped).length;
const csrfCount = routes.filter((r) => r.csrfWrapped).length;
const inputCount = routes.filter((r) => r.inputValidated).length;

const summary = `

## Summary

- Total routes: ${total}
- Auth-wrapped: ${authCount} (${pct(authCount)}%)
- Rate-limited: ${rlCount} (${pct(rlCount)}%)
- CSRF-protected: ${csrfCount} (${pct(csrfCount)}%)
- Input-validated: ${inputCount} (${pct(inputCount)}%)

## Highest-priority gaps

Routes that accept mutating methods (POST / PUT / PATCH / DELETE) AND have no auth wrapper AND no rate-limit:

| Route | Methods | File |
| --- | --- | --- |
${routes
  .filter((r) => !r.authWrapped && !r.rateLimitWrapped && r.methods.some((m) => ["POST","PUT","PATCH","DELETE"].includes(m)))
  .map((r) => `| \`${r.path}\` | ${r.methods.join(", ")} | \`${r.file.replace(process.cwd() + "/", "")}\` |`)
  .join("\n") || "_(none — every mutating route has at least auth or rate-limit)_"}
`;

const outPath = "docs/security/route-inventory.md";
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, header + rows + summary);
console.log(`Wrote ${total} routes to ${outPath}`);
